# Generated by Django 6.1.1 on 2026-10-06 02:58

import books.validators
import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17, validators=[books.validators.validate_isbn])),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('supplier_country', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('isbn'), models.Value('-'), models.Value('')), models.Value(' '), models.Value(''))), name='unique_book_normalized_isbn', violation_error_message='Ya existe un libro con este ISBN.')],
            },
        ),
    ]
